application.api.version: 1

spring:
  application:
    name: backend_2
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password: admin
  jpa:
    properties:
      hibernate:
        show_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect

#springdoc:
#  swagger-ui:
#    disable-swagger-default-url: true
#    path: /swagger/index.html