apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
  replicas: {{ .Values.backend.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}

    spec:
      containers:
        - name:  {{ .Values.backend.name }}
          image: {{ .Values.backend.image }}
          resources:
            limits:
              memory: "600Mi"
              cpu: "300m"
          ports:
            - containerPort: {{ .Values.backend.containerPort }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}
spec:
  selector:
    app: {{ .Values.backend.name }}
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.containerPort }}
