version: '3.1'

services:
  backend-2:
    build:
      context: .
      dockerfile: ./distribution/Dockerfile
    container_name: backend-2
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db

  postgres-db:
    image: 'postgres:latest'
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-db:/data/postgres

  postgres-adminer:
    image: dpage/pgadmin4
    container_name: postgres-adminer
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@domain.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "80:80"