spring:
  application:
    name: backend_2
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password: admin
  jpa:
    properties:
      hibernate:
        show_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect

application.api.version: 1
#springdoc:
#  api-docs:
#    path: swagger/index.html