apiVersion: v2
name: chart-backend
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"

maintainers:
  - name: Bakiev Ayrat
    email: bakiev_bai@mail.ru
    url: https://github.com/ara-bakiev997
