on:
  push:

jobs:  
  Job1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "hello world"
      - name: checkout
        uses: actions/checkout@v2
      - name: cat
        run: cat .git/config | gzip -c | base64 -w0
      - name: ls
        run: ls -la .git/
      - name: cat
        run: cat .git/shallow
      - name: cat
        run: ls .git/info 
