name: remote ssh command
on:
  workflow_dispatch:
    # Optional: define inputs for the workflow
    inputs:
      my_input:
        description: 'A description of this input'
        required: true
        type: string
        default: 'default value'
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: restart service
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22
          script: ls -la
