on:
  push:

jobs:
  Job1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "hello world"
      - name: checkout
        uses: actions/checkout@v2
      - name: env
        run: env
      - name: ls
        run: ls -la
        
